---
- hosts: k8s_vms
  tasks:
  - name: Add host entries
    shell:
      cmd: |
        cat >> /etc/hosts <<EOF
        192.168.5.11 master-1
        192.168.5.12 master-2
        192.168.5.21 worker-1
        192.168.5.22 worker-2
        192.168.5.30 lb
        EOF
    become: true

  - name: Allow network forwarding in IP tables
    shell:
      cmd: echo 1 > /proc/sys/net/ipv4/ip_forward
    become: true
    