---
- hosts: localhost
  tasks:
  - name: Create k8s_network vSwitch
    vmware_vswitch:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      switch: k8s_switch
    delegate_to: localhost

  - name: Create k8s_network port group
    vmware_portgroup:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      hosts: "{{ esxi_hostname }}"
      switch: k8s_switch
      portgroup: k8s_portgroup
    delegate_to: localhost

  - name: Create k8s router for virtual environment
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      validate_certs: no
      name: k8s-virtual-network-router
      state: poweredoff
      esxi_hostname: "{{ esxi_hostname }}"
      folder: "/{{ vcenter_datacenter }}/vm"
      template: ubuntu_vm_template
      networks:
        - name: VM Network
          ip: 192.168.1.200
          netmask: 255.255.255.0
          gateway: 192.168.1.1
          start_connected: true
          type: static
          dns_servers: 8.8.8.8
        - name: k8s_portgroup
          ip: 192.168.5.1
          netmask: 255.255.255.0
          start_connected: true
      customization:
        hostname: k8s-virtual-network-router
        dns_servers:
        - 8.8.8.8
      wait_for_customization: false
    delegate_to: localhost

  - name: Enable nics
    vmware_guest_network:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      validate_certs: no
      name: k8s-virtual-network-router
      gather_network_info: false
      networks:
        - name: VM Network
          esxi_hostname: "{{ vcenter_host }}"
          state: present
          device_type: vmxnet3
          connected: true
          start_connected: true
        - name: k8s_portgroup
          esxi_hostname: "{{ vcenter_host }}"
          state: present
          device_type: vmxnet3
          connected: true
          start_connected: true
    delegate_to: localhost
        
  - name: Turn VM on
    vmware_guest_powerstate:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      folder: "/{{ vcenter_datacenter }}/vm"
      validate_certs: no
      name: k8s-virtual-network-router
      state: powered-on
    delegate_to: localhost

  - name: Create k8s master API load balancer
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      validate_certs: no
      name: k8s-ha-lb
      state: poweredoff
      esxi_hostname: "{{ esxi_hostname }}"
      folder: "/{{ vcenter_datacenter }}/vm"
      template: ubuntu_vm_template
      networks:
        - name: k8s_portgroup
          ip: 192.168.5.30
          netmask: 255.255.255.0
          gateway: 192.168.5.1
          type: static
          dns_servers: 8.8.8.8
          start_connected: true
      customization:
        hostname: k8s-ha-lb
        dns_servers:
        - 8.8.8.8
      wait_for_customization: false
    delegate_to: localhost

  - name: Enable nics
    vmware_guest_network:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      validate_certs: no
      name: k8s-ha-lb
      gather_network_info: false
      networks:
        - name: k8s_portgroup
          esxi_hostname: "{{ vcenter_host }}"
          state: present
          device_type: vmxnet3
          connected: true
          start_connected: true
    delegate_to: localhost

  - name: Turn VM on
    vmware_guest_powerstate:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      folder: "/{{ vcenter_datacenter }}/vm"
      validate_certs: no
      name: k8s-ha-lb
      state: powered-on
    delegate_to: localhost